# Generated by Django 2.0.4 on 2018-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theword',
            name='word',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
